<?php

$title = 'Edit an instance';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute(
	'action', 
	$this->url('snide_redmon_instance/update')
);
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('host'));
echo $this->formRow($form->get('port'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();