 <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="{{ path('ringo_php_redmon') }}">ZF REDMON</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li <?php if ($route == 'snide_redmon') { ?> class="active"<?php } ?>><a href="<?= $this->url('snide_redmon') ?>">Dashboard</a></li>
            <?php if($instance) { ?>
                <li <?php if ($route == 'snide_redmon/client') { ?> class="active"<?php } ?>><a href="<?= $this->url('snide_redmon/client') ?>">Clients</a></li>
                <li <?php if ($route == 'snide_redmon/configuration') { ?> class="active"<?php } ?>><a href="<?= $this->url('snide_redmon/configuration') ?>">Configuration</a></li>
                <!-- <li><a href="">Console</a></li> -->
                <li <?php if ($route == 'snide_redmon_instance') { ?> class="active"<?php } ?>><a href="<?= $this->url('snide_redmon_instance') ?>">Administration</a></li>
            <?php }else { ?>
                <li class="disabled"><a href="#">Clients</a></li>
                <li class="disabled"><a href="#">Configuration</a></li>
                <li <?php if ($route == 'snide_redmon_instance') { ?> class="active"<?php } ?>><a href="<?= $this->url('snide_redmon_instance') ?>">Administration</a></li>
            <?php } ?>
          </ul>
          <ul class="nav pull-right">
            <li class="dropdown pull-right">
                <?php if(!is_object($instance)) { ?>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                     Choisissez une instance
                     <b class="caret"></b>
                   </a>
                <?php }else { ?>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Instance sélectionnée : <?= $instance->getName() ?>
                        <b class="caret"></b>
                    </a>
                <?php } ?>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <?php if(is_array($instances)) { 
                    foreach($instances as $instance) { ?>
                
                    <li>
                        <a tabindex="-1" href="<?= $this->url('snide_redmon_instance/select', array('id' => $instance->getId())) ?>"><?= $instance->getName() ?></a>
                    </li>
                <?php } 
                  }
                ?>
                </ul>
            </li>
            </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
</div>