    <h2>Clients</h2>
    <table class="table table-striped">
        <thead>
            <th>Host :</th>
            <th>Connection time</th>
            <th>Inactivity time</th>
            <th>Actual database</th>
            <th>Channels count</th>
            <th>qbuf</th>
            <th>last command</th>
        </thead>
    <?php if(is_array($clients)) { 
        foreach($clients as $client) { ?>
            <tr>
                <td><?= $client['addr'] ?></td>
                <td><?= $client['age']  ?></td>
                <td><?= $client['idle'] ?></td>
                <td><?= $client['db']   ?></td>
                <td><?= $client['sub']  ?></td>
                <td><?= $client['qbuf'] ?></td>
                <td><?= $client['cmd']  ?></td>
            </tr>
        <?php }
            }
        ?>
    </table>      
