   <h2>Configuration</h2>
    <table class="table table-striped">
        <thead>
            <th>Name </th>
            <th>Value </th>                    
        </thead>
    <?php if (is_object($configs)) {
        foreach($configs as $key => $value) { ?>
            <tr>
                <td><?= $key   ?></td>
                <td><?= $value ?></td>

            </tr>
    <?php }
        }
    ?>
    </table>         
